export const modalStyles = {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    bgcolor: "background.paper",
    borderRadius: "10px",
    width: "100%",
    maxWidth: 864,
    maxHeight: "90vh",
    height: "100%",
    overflow: "auto",
    boxShadow: 24,
    p: 4,
  };