import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@emotion/react";
import { theme } from "./theme/theme";
import CustomThemeProvider from "./theme/Provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const publicSans = localFont({
  src: './fonts/PublicSans-VariableFont_wght.ttf',
  variable: 'fonts-sans',
  weights: [100, 400, 500, 600, 700, 900],  // Use an array for the font weights
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={publicSans.variable} >
        {/* <CustomTh theme = {theme}> */}
        <CustomThemeProvider>
        {children}
        </CustomThemeProvider>
        {/* </CustomTh> */}
        
      </body>
    </html>
  );
}
